# generated by datamodel-codegen:
#   filename:  a2a_spec_fixed.json

from __future__ import annotations

from enum import Enum
from typing import Annotated, Any, Dict, List, Literal, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Model(RootModel[Any]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: Any


class A2AError(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    A discriminated union of all standard JSON-RPC and A2A-specific error types.
    """


class A2ARequest(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    A discriminated union representing all possible JSON-RPC 2.0 requests supported by the A2A specification.
    """


class In(Enum):
    """
    The location of the API key.
    """

    cookie = 'cookie'
    header = 'header'
    query = 'query'


class APIKeySecurityScheme(BaseModel):
    """
    Defines a security scheme using an API key.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    An optional description for the security scheme.
    """
    in_: Annotated[In, Field(alias='in')]
    """
    The location of the API key.
    """
    name: str
    """
    The name of the header, query, or cookie parameter to be used.
    """
    type: Literal['apiKey']
    """
    The type of the security scheme. Must be 'apiKey'.
    """


class AgentCardSignature(BaseModel):
    """
    AgentCardSignature represents a JWS signature of an AgentCard.
    This follows the JSON format of an RFC 7515 JSON Web Signature (JWS).
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    header: Dict[str, Any] | None = None
    """
    The unprotected JWS header values.
    """
    protected: str
    """
    The protected JWS header for the signature. This is a Base64url-encoded
    JSON object, as per RFC 7515.
    """
    signature: str
    """
    The computed signature, Base64url-encoded.
    """


class AgentExtension(BaseModel):
    """
    A declaration of a protocol extension supported by an Agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    A human-readable description of how this agent uses the extension.
    """
    params: Dict[str, Any] | None = None
    """
    Optional, extension-specific configuration parameters.
    """
    required: bool | None = None
    """
    If true, the client must understand and comply with the extension's requirements
    to interact with the agent.
    """
    uri: str
    """
    The unique URI identifying the extension.
    """


class AgentInterface(BaseModel):
    """
    Declares a combination of a target URL and a transport protocol for interacting with the agent.
    This allows agents to expose the same functionality over multiple transport mechanisms.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    transport: Annotated[str, Field(examples=['JSONRPC', 'GRPC', 'HTTP+JSON'])]
    """
    The transport protocol supported at this URL.
    """
    url: Annotated[
        str,
        Field(
            examples=[
                'https://api.example.com/a2a/v1',
                'https://grpc.example.com/a2a',
                'https://rest.example.com/v1',
            ]
        ),
    ]
    """
    The URL where this interface is available. Must be a valid absolute HTTPS URL in production.
    """


class AgentProvider(BaseModel):
    """
    Represents the service provider of an agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    organization: str
    """
    The name of the agent provider's organization.
    """
    url: str
    """
    A URL for the agent provider's website or relevant documentation.
    """


class AgentSkill(BaseModel):
    """
    Represents a distinct capability or function that an agent can perform.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str
    """
    A detailed description of the skill, intended to help clients or users
    understand its purpose and functionality.
    """
    examples: Annotated[
        List[str] | None, Field(examples=[['I need a recipe for bread']])
    ] = None
    """
    Example prompts or scenarios that this skill can handle. Provides a hint to
    the client on how to use the skill.
    """
    id: str
    """
    A unique identifier for the agent's skill.
    """
    input_modes: Annotated[List[str] | None, Field(alias='inputModes')] = None
    """
    The set of supported input MIME types for this skill, overriding the agent's defaults.
    """
    name: str
    """
    A human-readable name for the skill.
    """
    output_modes: Annotated[List[str] | None, Field(alias='outputModes')] = None
    """
    The set of supported output MIME types for this skill, overriding the agent's defaults.
    """
    security: Annotated[
        List[Dict[str, List[str]]] | None, Field(examples=[[{'google': ['oidc']}]])
    ] = None
    """
    Security schemes necessary for the agent to leverage this skill.
    As in the overall AgentCard.security, this list represents a logical OR of security
    requirement objects. Each object is a set of security schemes that must be used together
    (a logical AND).
    """
    tags: Annotated[
        List[str], Field(examples=[['cooking', 'customer support', 'billing']])
    ]
    """
    A set of keywords describing the skill's capabilities.
    """


class AuthenticatedExtendedCardNotConfiguredError(BaseModel):
    """
    An A2A-specific error indicating that the agent does not have an Authenticated Extended Card configured
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32007]
    """
    The error code for when an authenticated extended card is not configured.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class AuthorizationCodeOAuthFlow(BaseModel):
    """
    Defines configuration details for the OAuth 2.0 Authorization Code flow.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    authorization_url: Annotated[str, Field(alias='authorizationUrl')]
    """
    The authorization URL to be used for this flow.
    This MUST be a URL and use TLS.
    """
    refresh_url: Annotated[str | None, Field(alias='refreshUrl')] = None
    """
    The URL to be used for obtaining refresh tokens.
    This MUST be a URL and use TLS.
    """
    scopes: Dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope
    name and a short description for it.
    """
    token_url: Annotated[str, Field(alias='tokenUrl')]
    """
    The token URL to be used for this flow.
    This MUST be a URL and use TLS.
    """


class CancelTaskResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/cancel` method.
    """


class ClientCredentialsOAuthFlow(BaseModel):
    """
    Defines configuration details for the OAuth 2.0 Client Credentials flow.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    refresh_url: Annotated[str | None, Field(alias='refreshUrl')] = None
    """
    The URL to be used for obtaining refresh tokens. This MUST be a URL.
    """
    scopes: Dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope
    name and a short description for it.
    """
    token_url: Annotated[str, Field(alias='tokenUrl')]
    """
    The token URL to be used for this flow. This MUST be a URL.
    """


class ContentTypeNotSupportedError(BaseModel):
    """
    An A2A-specific error indicating an incompatibility between the requested
    content types and the agent's capabilities.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32005]
    """
    The error code for an unsupported content type.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class DataPart(BaseModel):
    """
    Represents a structured data segment (e.g., JSON) within a message or artifact.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    data: Dict[str, Any]
    """
    The structured data content.
    """
    kind: Literal['data']
    """
    The type of this part, used as a discriminator. Always 'data'.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with this part.
    """


class DeleteTaskPushNotificationConfigParams(BaseModel):
    """
    Defines parameters for deleting a specific push notification configuration for a task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    The unique identifier (e.g. UUID) of the task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with the request.
    """
    push_notification_config_id: Annotated[str, Field(alias='pushNotificationConfigId')]
    """
    The ID of the push notification configuration to delete.
    """


class DeleteTaskPushNotificationConfigRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/pushNotificationConfig/delete` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/pushNotificationConfig/delete']
    """
    The method name. Must be 'tasks/pushNotificationConfig/delete'.
    """
    params: DeleteTaskPushNotificationConfigParams
    """
    The parameters identifying the push notification configuration to delete.
    """


class DeleteTaskPushNotificationConfigResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/pushNotificationConfig/delete` method.
    """


class DeleteTaskPushNotificationConfigSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/pushNotificationConfig/delete` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: None
    """
    The result is null on successful deletion.
    """


class FileBase(BaseModel):
    """
    Defines base properties for a file.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    The MIME type of the file (e.g., "application/pdf").
    """
    name: str | None = None
    """
    An optional name for the file (e.g., "document.pdf").
    """


class FilePart(BaseModel):
    """
    Represents a file segment within a message or artifact. The file content can be
    provided either directly as bytes or as a URI.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    file: None = None
    """
    The file content, represented as either a URI or as base64-encoded bytes.
    """
    kind: Literal['file']
    """
    The type of this part, used as a discriminator. Always 'file'.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with this part.
    """


class FileWithBytes(BaseModel):
    """
    Represents a file with its content provided directly as a base64-encoded string.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    bytes: str
    """
    The base64-encoded content of the file.
    """
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    The MIME type of the file (e.g., "application/pdf").
    """
    name: str | None = None
    """
    An optional name for the file (e.g., "document.pdf").
    """


class FileWithUri(BaseModel):
    """
    Represents a file with its content located at a specific URI.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    mime_type: Annotated[str | None, Field(alias='mimeType')] = None
    """
    The MIME type of the file (e.g., "application/pdf").
    """
    name: str | None = None
    """
    An optional name for the file (e.g., "document.pdf").
    """
    uri: str
    """
    A URL pointing to the file's content.
    """


class GetAuthenticatedExtendedCardRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `agent/getAuthenticatedExtendedCard` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['agent/getAuthenticatedExtendedCard']
    """
    The method name. Must be 'agent/getAuthenticatedExtendedCard'.
    """


class GetAuthenticatedExtendedCardResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `agent/getAuthenticatedExtendedCard` method.
    """


class GetTaskPushNotificationConfigParams(BaseModel):
    """
    Defines parameters for fetching a specific push notification configuration for a task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    The unique identifier (e.g. UUID) of the task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with the request.
    """
    push_notification_config_id: Annotated[
        str | None, Field(alias='pushNotificationConfigId')
    ] = None
    """
    The ID of the push notification configuration to retrieve.
    """


class GetTaskPushNotificationConfigRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/pushNotificationConfig/get` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/pushNotificationConfig/get']
    """
    The method name. Must be 'tasks/pushNotificationConfig/get'.
    """
    params: None = None
    """
    The parameters for getting a push notification configuration.
    """


class GetTaskPushNotificationConfigResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/pushNotificationConfig/get` method.
    """


class GetTaskResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/get` method.
    """


class HTTPAuthSecurityScheme(BaseModel):
    """
    Defines a security scheme using HTTP authentication.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    bearer_format: Annotated[str | None, Field(alias='bearerFormat')] = None
    """
    A hint to the client to identify how the bearer token is formatted (e.g., "JWT").
    This is primarily for documentation purposes.
    """
    description: str | None = None
    """
    An optional description for the security scheme.
    """
    scheme: str
    """
    The name of the HTTP Authentication scheme to be used in the Authorization header,
    as defined in RFC7235 (e.g., "Bearer").
    This value should be registered in the IANA Authentication Scheme registry.
    """
    type: Literal['http']
    """
    The type of the security scheme. Must be 'http'.
    """


class ImplicitOAuthFlow(BaseModel):
    """
    Defines configuration details for the OAuth 2.0 Implicit flow.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    authorization_url: Annotated[str, Field(alias='authorizationUrl')]
    """
    The authorization URL to be used for this flow. This MUST be a URL.
    """
    refresh_url: Annotated[str | None, Field(alias='refreshUrl')] = None
    """
    The URL to be used for obtaining refresh tokens. This MUST be a URL.
    """
    scopes: Dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope
    name and a short description for it.
    """


class InternalError(BaseModel):
    """
    An error indicating an internal error on the server.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32603]
    """
    The error code for an internal server error.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class InvalidAgentResponseError(BaseModel):
    """
    An A2A-specific error indicating that the agent returned a response that
    does not conform to the specification for the current method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32006]
    """
    The error code for an invalid agent response.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class InvalidParamsError(BaseModel):
    """
    An error indicating that the method parameters are invalid.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32602]
    """
    The error code for an invalid parameters error.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class InvalidRequestError(BaseModel):
    """
    An error indicating that the JSON sent is not a valid Request object.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32600]
    """
    The error code for an invalid request.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class JSONParseError(BaseModel):
    """
    An error indicating that the server received invalid JSON.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32700]
    """
    The error code for a JSON parse error.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class JSONRPCError(BaseModel):
    """
    Represents a JSON-RPC 2.0 Error object, included in an error response.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: int
    """
    A number that indicates the error type that occurred.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    A string providing a short description of the error.
    """


class JSONRPCErrorResponse(BaseModel):
    """
    Represents a JSON-RPC 2.0 Error Response object.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    error: None = None
    """
    An object describing the error that occurred.
    """
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """


class JSONRPCMessage(BaseModel):
    """
    Defines the base structure for any JSON-RPC 2.0 request, response, or notification.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    A unique identifier established by the client. It must be a String, a Number, or null.
    The server must reply with the same value in the response. This property is omitted for notifications.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """


class JSONRPCRequest(BaseModel):
    """
    Represents a JSON-RPC 2.0 Request object.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    A unique identifier established by the client. It must be a String, a Number, or null.
    The server must reply with the same value in the response. This property is omitted for notifications.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: str
    """
    A string containing the name of the method to be invoked.
    """
    params: Dict[str, Any] | None = None
    """
    A structured value holding the parameter values to be used during the method invocation.
    """


class JSONRPCResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    A discriminated union representing all possible JSON-RPC 2.0 responses
    for the A2A specification methods.
    """


class JSONRPCSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC 2.0 Response object.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Any
    """
    The value of this member is determined by the method invoked on the Server.
    """


class ListTaskPushNotificationConfigParams(BaseModel):
    """
    Defines parameters for listing all push notification configurations associated with a task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    The unique identifier (e.g. UUID) of the task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with the request.
    """


class ListTaskPushNotificationConfigRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/pushNotificationConfig/list` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/pushNotificationConfig/list']
    """
    The method name. Must be 'tasks/pushNotificationConfig/list'.
    """
    params: ListTaskPushNotificationConfigParams
    """
    The parameters identifying the task whose configurations are to be listed.
    """


class ListTaskPushNotificationConfigResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/pushNotificationConfig/list` method.
    """


class Role(Enum):
    """
    Identifies the sender of the message. `user` for the client, `agent` for the service.
    """

    agent = 'agent'
    user = 'user'


class MethodNotFoundError(BaseModel):
    """
    An error indicating that the requested method does not exist or is not available.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32601]
    """
    The error code for a method not found error.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class MutualTLSSecurityScheme(BaseModel):
    """
    Defines a security scheme using mTLS authentication.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    An optional description for the security scheme.
    """
    type: Literal['mutualTLS']
    """
    The type of the security scheme. Must be 'mutualTLS'.
    """


class OpenIdConnectSecurityScheme(BaseModel):
    """
    Defines a security scheme using OpenID Connect.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    An optional description for the security scheme.
    """
    open_id_connect_url: Annotated[str, Field(alias='openIdConnectUrl')]
    """
    The OpenID Connect Discovery URL for the OIDC provider's metadata.
    """
    type: Literal['openIdConnect']
    """
    The type of the security scheme. Must be 'openIdConnect'.
    """


class Part(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    A discriminated union representing a part of a message or artifact, which can
    be text, a file, or structured data.
    """


class PartBase(BaseModel):
    """
    Defines base properties common to all message or artifact parts.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with this part.
    """


class PasswordOAuthFlow(BaseModel):
    """
    Defines configuration details for the OAuth 2.0 Resource Owner Password flow.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    refresh_url: Annotated[str | None, Field(alias='refreshUrl')] = None
    """
    The URL to be used for obtaining refresh tokens. This MUST be a URL.
    """
    scopes: Dict[str, str]
    """
    The available scopes for the OAuth2 security scheme. A map between the scope
    name and a short description for it.
    """
    token_url: Annotated[str, Field(alias='tokenUrl')]
    """
    The token URL to be used for this flow. This MUST be a URL.
    """


class PushNotificationAuthenticationInfo(BaseModel):
    """
    Defines authentication details for a push notification endpoint.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    credentials: str | None = None
    """
    Optional credentials required by the push notification endpoint.
    """
    schemes: List[str]
    """
    A list of supported authentication schemes (e.g., 'Basic', 'Bearer').
    """


class PushNotificationConfig(BaseModel):
    """
    Defines the configuration for setting up push notifications for task updates.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    authentication: PushNotificationAuthenticationInfo | None = None
    """
    Optional authentication details for the agent to use when calling the notification URL.
    """
    id: str | None = None
    """
    A unique identifier (e.g. UUID) for the push notification configuration, set by the client
    to support multiple notification callbacks.
    """
    token: str | None = None
    """
    A unique token for this task or session to validate incoming push notifications.
    """
    url: str
    """
    The callback URL where the agent should send push notifications.
    """


class PushNotificationNotSupportedError(BaseModel):
    """
    An A2A-specific error indicating that the agent does not support push notifications.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32003]
    """
    The error code for when push notifications are not supported.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class SecurityScheme(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Defines a security scheme that can be used to secure an agent's endpoints.
    This is a discriminated union type based on the OpenAPI 3.0 Security Scheme Object.
    """


class SecuritySchemeBase(BaseModel):
    """
    Defines base properties shared by all security scheme objects.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    An optional description for the security scheme.
    """


class SendMessageResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `message/send` method.
    """


class SendMessageSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `message/send` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: None = None
    """
    The result, which can be a direct reply Message or the initial Task object.
    """


class SendStreamingMessageResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `message/stream` method.
    """


class SendStreamingMessageSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `message/stream` method.
    The server may send multiple response objects for a single request.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: None = None
    """
    The result, which can be a Message, Task, or a streaming update event.
    """


class SetTaskPushNotificationConfigResponse(RootModel[None]):
    model_config = ConfigDict(
        populate_by_name=True,
    )
    root: None
    """
    Represents a JSON-RPC response for the `tasks/pushNotificationConfig/set` method.
    """


class TaskIdParams(BaseModel):
    """
    Defines parameters containing a task ID, used for simple task operations.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str
    """
    The unique identifier (e.g. UUID) of the task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with the request.
    """


class TaskNotCancelableError(BaseModel):
    """
    An A2A-specific error indicating that the task is in a state where it cannot be canceled.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32002]
    """
    The error code for a task that cannot be canceled.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class TaskNotFoundError(BaseModel):
    """
    An A2A-specific error indicating that the requested task ID was not found.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32001]
    """
    The error code for a task not found error.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class TaskPushNotificationConfig(BaseModel):
    """
    A container associating a push notification configuration with a specific task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    push_notification_config: Annotated[
        PushNotificationConfig, Field(alias='pushNotificationConfig')
    ]
    """
    The push notification configuration for this task.
    """
    task_id: Annotated[str, Field(alias='taskId')]
    """
    The unique identifier (e.g. UUID) of the task.
    """


class TaskQueryParams(BaseModel):
    """
    Defines parameters for querying a task, with an option to limit history length.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    history_length: Annotated[int | None, Field(alias='historyLength')] = None
    """
    The number of most recent messages from the task's history to retrieve.
    """
    id: str
    """
    The unique identifier (e.g. UUID) of the task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with the request.
    """


class TaskResubscriptionRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/resubscribe` method, used to resume a streaming connection.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/resubscribe']
    """
    The method name. Must be 'tasks/resubscribe'.
    """
    params: TaskIdParams
    """
    The parameters identifying the task to resubscribe to.
    """


class TaskState(Enum):
    """
    Defines the lifecycle states of a Task.
    """

    submitted = 'submitted'
    working = 'working'
    input_required = 'input-required'
    completed = 'completed'
    canceled = 'canceled'
    failed = 'failed'
    rejected = 'rejected'
    auth_required = 'auth-required'
    unknown = 'unknown'


class TextPart(BaseModel):
    """
    Represents a text segment within a message or artifact.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    kind: Literal['text']
    """
    The type of this part, used as a discriminator. Always 'text'.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata associated with this part.
    """
    text: str
    """
    The string content of the text part.
    """


class TransportProtocol(Enum):
    """
    Supported A2A transport protocols.
    """

    jsonrpc = 'JSONRPC'
    grpc = 'GRPC'
    http_json = 'HTTP+JSON'


class UnsupportedOperationError(BaseModel):
    """
    An A2A-specific error indicating that the requested operation is not supported by the agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    code: Literal[-32004]
    """
    The error code for an unsupported operation.
    """
    data: Any | None = None
    """
    A primitive or structured value containing additional information about the error.
    This may be omitted.
    """
    message: str
    """
    The error message.
    """


class AgentCapabilities(BaseModel):
    """
    Defines optional capabilities supported by an agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    extensions: List[AgentExtension] | None = None
    """
    A list of protocol extensions supported by the agent.
    """
    push_notifications: Annotated[bool | None, Field(alias='pushNotifications')] = None
    """
    Indicates if the agent supports sending push notifications for asynchronous task updates.
    """
    state_transition_history: Annotated[
        bool | None, Field(alias='stateTransitionHistory')
    ] = None
    """
    Indicates if the agent provides a history of state transitions for a task.
    """
    streaming: bool | None = None
    """
    Indicates if the agent supports Server-Sent Events (SSE) for streaming responses.
    """


class AgentCard(BaseModel):
    """
    The AgentCard is a self-describing manifest for an agent. It provides essential
    metadata including the agent's identity, capabilities, skills, supported
    communication methods, and security requirements.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    additional_interfaces: Annotated[
        List[AgentInterface] | None, Field(alias='additionalInterfaces')
    ] = None
    """
    A list of additional supported interfaces (transport and URL combinations).
    This allows agents to expose multiple transports, potentially at different URLs.

    Best practices:
    - SHOULD include all supported transports for completeness
    - SHOULD include an entry matching the main 'url' and 'preferredTransport'
    - MAY reuse URLs if multiple transports are available at the same endpoint
    - MUST accurately declare the transport available at each URL

    Clients can select any interface from this list based on their transport capabilities
    and preferences. This enables transport negotiation and fallback scenarios.
    """
    capabilities: AgentCapabilities
    """
    A declaration of optional capabilities supported by the agent.
    """
    default_input_modes: Annotated[List[str], Field(alias='defaultInputModes')]
    """
    Default set of supported input MIME types for all skills, which can be
    overridden on a per-skill basis.
    """
    default_output_modes: Annotated[List[str], Field(alias='defaultOutputModes')]
    """
    Default set of supported output MIME types for all skills, which can be
    overridden on a per-skill basis.
    """
    description: Annotated[
        str, Field(examples=['Agent that helps users with recipes and cooking.'])
    ]
    """
    A human-readable description of the agent, assisting users and other agents
    in understanding its purpose.
    """
    documentation_url: Annotated[str | None, Field(alias='documentationUrl')] = None
    """
    An optional URL to the agent's documentation.
    """
    icon_url: Annotated[str | None, Field(alias='iconUrl')] = None
    """
    An optional URL to an icon for the agent.
    """
    name: Annotated[str, Field(examples=['Recipe Agent'])]
    """
    A human-readable name for the agent.
    """
    preferred_transport: Annotated[
        str | None,
        Field(alias='preferredTransport', examples=['JSONRPC', 'GRPC', 'HTTP+JSON']),
    ] = 'JSONRPC'
    """
    The transport protocol for the preferred endpoint (the main 'url' field).
    If not specified, defaults to 'JSONRPC'.

    IMPORTANT: The transport specified here MUST be available at the main 'url'.
    This creates a binding between the main URL and its supported transport protocol.
    Clients should prefer this transport and URL combination when both are supported.
    """
    protocol_version: Annotated[str, Field(alias='protocolVersion')]
    """
    The version of the A2A protocol this agent supports.
    """
    provider: AgentProvider | None = None
    """
    Information about the agent's service provider.
    """
    security: Annotated[
        List[Dict[str, List[str]]] | None,
        Field(examples=[[{'oauth': ['read']}, {'api-key': [], 'mtls': []}]]),
    ] = None
    """
    A list of security requirement objects that apply to all agent interactions. Each object
    lists security schemes that can be used. Follows the OpenAPI 3.0 Security Requirement Object.
    This list can be seen as an OR of ANDs. Each object in the list describes one possible
    set of security requirements that must be present on a request. This allows specifying,
    for example, "callers must either use OAuth OR an API Key AND mTLS."
    """
    security_schemes: Annotated[
        Dict[str, SecurityScheme] | None, Field(alias='securitySchemes')
    ] = None
    """
    A declaration of the security schemes available to authorize requests. The key is the
    scheme name. Follows the OpenAPI 3.0 Security Scheme Object.
    """
    signatures: List[AgentCardSignature] | None = None
    """
    JSON Web Signatures computed for this AgentCard.
    """
    skills: List[AgentSkill]
    """
    The set of skills, or distinct capabilities, that the agent can perform.
    """
    supports_authenticated_extended_card: Annotated[
        bool | None, Field(alias='supportsAuthenticatedExtendedCard')
    ] = None
    """
    If true, the agent can provide an extended agent card with additional details
    to authenticated users. Defaults to false.
    """
    url: Annotated[str, Field(examples=['https://api.example.com/a2a/v1'])]
    """
    The preferred endpoint URL for interacting with the agent.
    This URL MUST support the transport specified by 'preferredTransport'.
    """
    version: Annotated[str, Field(examples=['1.0.0'])]
    """
    The agent's own version number. The format is defined by the provider.
    """


class Artifact(BaseModel):
    """
    Represents a file, data structure, or other resource generated by an agent during a task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    artifact_id: Annotated[str, Field(alias='artifactId')]
    """
    A unique identifier (e.g. UUID) for the artifact within the scope of the task.
    """
    description: str | None = None
    """
    An optional, human-readable description of the artifact.
    """
    extensions: List[str] | None = None
    """
    The URIs of extensions that are relevant to this artifact.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions. The key is an extension-specific identifier.
    """
    name: str | None = None
    """
    An optional, human-readable name for the artifact.
    """
    parts: List[Part]
    """
    An array of content parts that make up the artifact.
    """


class CancelTaskRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/cancel` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/cancel']
    """
    The method name. Must be 'tasks/cancel'.
    """
    params: TaskIdParams
    """
    The parameters identifying the task to cancel.
    """


class GetAuthenticatedExtendedCardSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `agent/getAuthenticatedExtendedCard` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: AgentCard
    """
    The result is an Agent Card object.
    """


class GetTaskPushNotificationConfigSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/pushNotificationConfig/get` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: TaskPushNotificationConfig
    """
    The result, containing the requested push notification configuration.
    """


class GetTaskRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/get` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/get']
    """
    The method name. Must be 'tasks/get'.
    """
    params: TaskQueryParams
    """
    The parameters for querying a task.
    """


class ListTaskPushNotificationConfigSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/pushNotificationConfig/list` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: List[TaskPushNotificationConfig]
    """
    The result, containing an array of all push notification configurations for the task.
    """


class Message(BaseModel):
    """
    Represents a single message in the conversation between a user and an agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    context_id: Annotated[str | None, Field(alias='contextId')] = None
    """
    The context ID for this message, used to group related interactions.
    """
    extensions: List[str] | None = None
    """
    The URIs of extensions that are relevant to this message.
    """
    kind: Literal['message']
    """
    The type of this object, used as a discriminator. Always 'message' for a Message.
    """
    message_id: Annotated[str, Field(alias='messageId')]
    """
    A unique identifier for the message, typically a UUID, generated by the sender.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions. The key is an extension-specific identifier.
    """
    parts: List[Part]
    """
    An array of content parts that form the message body. A message can be
    composed of multiple parts of different types (e.g., text and files).
    """
    reference_task_ids: Annotated[List[str] | None, Field(alias='referenceTaskIds')] = (
        None
    )
    """
    A list of other task IDs that this message references for additional context.
    """
    role: Role
    """
    Identifies the sender of the message. `user` for the client, `agent` for the service.
    """
    task_id: Annotated[str | None, Field(alias='taskId')] = None
    """
    The ID of the task this message is part of. Can be omitted for the first message of a new task.
    """


class MessageSendConfiguration(BaseModel):
    """
    Defines configuration options for a `message/send` or `message/stream` request.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    accepted_output_modes: Annotated[
        List[str] | None, Field(alias='acceptedOutputModes')
    ] = None
    """
    A list of output MIME types the client is prepared to accept in the response.
    """
    blocking: bool | None = None
    """
    If true, the client will wait for the task to complete. The server may reject this if the task is long-running.
    """
    history_length: Annotated[int | None, Field(alias='historyLength')] = None
    """
    The number of most recent messages from the task's history to retrieve in the response.
    """
    push_notification_config: Annotated[
        PushNotificationConfig | None, Field(alias='pushNotificationConfig')
    ] = None
    """
    Configuration for the agent to send push notifications for updates after the initial response.
    """


class MessageSendParams(BaseModel):
    """
    Defines the parameters for a request to send a message to an agent. This can be used
    to create a new task, continue an existing one, or restart a task.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    configuration: MessageSendConfiguration | None = None
    """
    Optional configuration for the send request.
    """
    message: Message
    """
    The message object being sent to the agent.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions.
    """


class OAuthFlows(BaseModel):
    """
    Defines the configuration for the supported OAuth 2.0 flows.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    authorization_code: Annotated[
        AuthorizationCodeOAuthFlow | None, Field(alias='authorizationCode')
    ] = None
    """
    Configuration for the OAuth Authorization Code flow. Previously called accessCode in OpenAPI 2.0.
    """
    client_credentials: Annotated[
        ClientCredentialsOAuthFlow | None, Field(alias='clientCredentials')
    ] = None
    """
    Configuration for the OAuth Client Credentials flow. Previously called application in OpenAPI 2.0.
    """
    implicit: ImplicitOAuthFlow | None = None
    """
    Configuration for the OAuth Implicit flow.
    """
    password: PasswordOAuthFlow | None = None
    """
    Configuration for the OAuth Resource Owner Password flow.
    """


class SendMessageRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `message/send` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['message/send']
    """
    The method name. Must be 'message/send'.
    """
    params: MessageSendParams
    """
    The parameters for sending a message.
    """


class SendStreamingMessageRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `message/stream` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['message/stream']
    """
    The method name. Must be 'message/stream'.
    """
    params: MessageSendParams
    """
    The parameters for sending a message.
    """


class SetTaskPushNotificationConfigRequest(BaseModel):
    """
    Represents a JSON-RPC request for the `tasks/pushNotificationConfig/set` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int
    """
    The identifier for this request.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    method: Literal['tasks/pushNotificationConfig/set']
    """
    The method name. Must be 'tasks/pushNotificationConfig/set'.
    """
    params: TaskPushNotificationConfig
    """
    The parameters for setting the push notification configuration.
    """


class SetTaskPushNotificationConfigSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/pushNotificationConfig/set` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: TaskPushNotificationConfig
    """
    The result, containing the configured push notification settings.
    """


class TaskArtifactUpdateEvent(BaseModel):
    """
    An event sent by the agent to notify the client that an artifact has been
    generated or updated. This is typically used in streaming models.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    append: bool | None = None
    """
    If true, the content of this artifact should be appended to a previously sent artifact with the same ID.
    """
    artifact: Artifact
    """
    The artifact that was generated or updated.
    """
    context_id: Annotated[str, Field(alias='contextId')]
    """
    The context ID associated with the task.
    """
    kind: Literal['artifact-update']
    """
    The type of this event, used as a discriminator. Always 'artifact-update'.
    """
    last_chunk: Annotated[bool | None, Field(alias='lastChunk')] = None
    """
    If true, this is the final chunk of the artifact.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions.
    """
    task_id: Annotated[str, Field(alias='taskId')]
    """
    The ID of the task this artifact belongs to.
    """


class TaskStatus(BaseModel):
    """
    Represents the status of a task at a specific point in time.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    message: Message | None = None
    """
    An optional, human-readable message providing more details about the current status.
    """
    state: TaskState
    """
    The current state of the task's lifecycle.
    """
    timestamp: Annotated[str | None, Field(examples=['2023-10-27T10:00:00Z'])] = None
    """
    An ISO 8601 datetime string indicating when this status was recorded.
    """


class TaskStatusUpdateEvent(BaseModel):
    """
    An event sent by the agent to notify the client of a change in a task's status.
    This is typically used in streaming or subscription models.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    context_id: Annotated[str, Field(alias='contextId')]
    """
    The context ID associated with the task.
    """
    final: bool
    """
    If true, this is the final event in the stream for this interaction.
    """
    kind: Literal['status-update']
    """
    The type of this event, used as a discriminator. Always 'status-update'.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions.
    """
    status: TaskStatus
    """
    The new status of the task.
    """
    task_id: Annotated[str, Field(alias='taskId')]
    """
    The ID of the task that was updated.
    """


class OAuth2SecurityScheme(BaseModel):
    """
    Defines a security scheme using OAuth 2.0.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    description: str | None = None
    """
    An optional description for the security scheme.
    """
    flows: OAuthFlows
    """
    An object containing configuration information for the supported OAuth 2.0 flows.
    """
    oauth2_metadata_url: Annotated[str | None, Field(alias='oauth2MetadataUrl')] = None
    """
    URL to the oauth2 authorization server metadata
    [RFC8414](https://datatracker.ietf.org/doc/html/rfc8414). TLS is required.
    """
    type: Literal['oauth2']
    """
    The type of the security scheme. Must be 'oauth2'.
    """


class Task(BaseModel):
    """
    Represents a single, stateful operation or conversation between a client and an agent.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    artifacts: List[Artifact] | None = None
    """
    A collection of artifacts generated by the agent during the execution of the task.
    """
    context_id: Annotated[str, Field(alias='contextId')]
    """
    A server-generated unique identifier (e.g. UUID) for maintaining context across multiple related tasks or interactions.
    """
    history: List[Message] | None = None
    """
    An array of messages exchanged during the task, representing the conversation history.
    """
    id: str
    """
    A unique identifier (e.g. UUID) for the task, generated by the server for a new task.
    """
    kind: Literal['task']
    """
    The type of this object, used as a discriminator. Always 'task' for a Task.
    """
    metadata: Dict[str, Any] | None = None
    """
    Optional metadata for extensions. The key is an extension-specific identifier.
    """
    status: TaskStatus
    """
    The current status of the task, including its state and a descriptive message.
    """


class CancelTaskSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/cancel` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task
    """
    The result, containing the final state of the canceled Task object.
    """


class GetTaskSuccessResponse(BaseModel):
    """
    Represents a successful JSON-RPC response for the `tasks/get` method.
    """

    model_config = ConfigDict(
        populate_by_name=True,
    )
    id: str | int | None = None
    """
    The identifier established by the client.
    """
    jsonrpc: Literal['2.0']
    """
    The version of the JSON-RPC protocol. MUST be exactly "2.0".
    """
    result: Task
    """
    The result, containing the requested Task object.
    """
